baseURL = "https://ysf-lsr.github.io/blog/"
title = "YSF Light Side Robotics"
theme = "PaperMod"
# googleAnalytics = "UA-123-45"
disableKinds = ["RSS"]
summarylength = 80
HasCJKLanguage = true
canonifyurls = true
publishDir = "docs"
enableGitInfo = true
DefaultContentLanguage = "ja"

[minify]
disableXML = true
minifyOutput = true

[params]
title = "YSF Light Side Robotics"
DateFormat = "2006/1/2"
description = "私たちLSRは、横浜市立横浜サイエンスフロンティア高等学校・附属中学校 ロボット探究部所属のチームです。"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
env = "production"
defaultTheme = "light"
disableThemeToggle = true
# ShowShareButtons = true
ShowPostNavLinks = true
# ShowBreadCrumbs = true
disableScrollToTop = false

	[params.assets]
	disableHLJS = true
	favicon = "apple-touch-icon.png"
	favicon16x16 = "apple-touch-icon.png"
	favicon32x32 = "apple-touch-icon.png"
	apple_touch_icon = "apple-touch-icon.png"
	theme_color = "#f80015"

	[params.label]
	text = "YSF LSR"
	# icon = "image/logo.svg"

	[params.homeInfoParams]
	Title = "YSF Light Side Robotics"

	# [params.analytics.google]
	# SiteVerificationTag = "XYZabc"

	# [params.cover]
	# hidden = true
	# hiddenInList = true
	# hiddenInSingle = true

	[params.fuseOpts]
	isCaseSensitive = false
	shouldSort = true
	location = 0
	distance = 1_000
	threshold = 0.4
	minMatchCharLength = 0
	keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
name = "ABOUT"
url = "about/"
weight = 1

[[menu.main]]
name = "PRIZES"
url = "prizes/"
weight = 2

[[menu.main]]
name = "BLOG"
url = "posts/"
weight = 3